/**
 * Vegatables And Fruits
 * An API for getting vegatables fruits
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Entity { 
    id?: number;
    type?: Entity.TypeEnum;
    name?: string;
}
export namespace Entity {
    export type TypeEnum = 'vegetables' | 'fruit';
    export const TypeEnum = {
        Vegetables: 'vegetables' as TypeEnum,
        Fruit: 'fruit' as TypeEnum
    };
}


